### ISSUE TITLE
Change require path in examples

### ISSUE THREAD

**Issue by Nic2012** [TypedProject/ts-gphoto2-driver#6]
When users have installed the driver from npm, fetch examples from github and run it immediately afterwards, scripts ends with an exception:
```
node camera.js
module.js:538
    throw err;
    ^
Error: Cannot find module '../src'
    at Function.Module._resolveFilename (module.js:536:15)...
```
Change require path e.g. from
`const { CameraList, closeQuietly } = require('../src');`
to
`const { CameraList, closeQuietly } = require('@typedproject/gphoto2-driver');`

@Romakita: When its ok for y, I ll fix it.

**Comment by Romakita** [comment]
You shouldn't change the path. In the readme, it's explained, you need to run `npm run develop` before run an example :)

**Comment by Nic2012** [comment]
When I run it, it failed:
```
npm run develop

> @typedproject/gphoto2-driver@2.0.0 develop /home/pi/ts-gphoto2-driver
> tsc --project tsconfig.json -w

sh: 1: tsc: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT...
```
Because I have NOT installed type script dependencies and I am a consumer who has installed the driver from npm only. Not everybody wants to install the whole develop stack to get familiar with the library.

So I assume when the require path is set to `require('@typedproject/gphoto2-driver')` then example will run by npm package or installation from develop stack.

**Comment by goooseman** [comment]
@Nic2012 examples are used in development to test some features.
if we make it to require from `'@typedproject/gphoto2-driver'`, it will make it harder to develop and test.

But we can do like this:
```
const { CameraList, closeQuietly } = require('../src');
// If you launch this example not from library folder, change the previous line to:
// const { CameraList, closeQuietly } = require('@typedproject/gphoto2-driver');
```
@Nic2012 @Romakita What do you think about this solution?

**Comment by Romakita** [comment]
@Nic2012 
We have two way to run examples. 
1)
If a developer want test the examples, it just copy/paste the example in his project and adapt the require('../src') by `require('@typedproject/gphoto2-driver')`.

2)
If the developer checkout the repository and run `npm install`. Typescript will be automatically installed. Finally, developer can run `npm run develop` to build the source correctly (in dev mod) and run examples.

---

It's strange if you have a tsc error. Because, typescript is declared as devDependencies in the package.json and it should be installed with `npm install`.

**Comment by Romakita** [comment]
@goooseman I'm ok for that :)

**Comment by goooseman** [comment]
@Romakita I'll send a PR.

**Comment by goooseman** [comment]
@Romakita sent a PR
https://github.com/TypedProject/ts-gphoto2-driver/pull/7

**Comment by Romakita** [comment]
ok it's done :)
